file:
  client-path: /me
  storage-location: D:/ISTAD/ITE3rd/ite-img/
  basae-uri: http://localhost:${server.port}${file.client-path}/
spring:
  jpa:
    hibernate:
    # ddl-auto: create-drop
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}

  application:
    name: ite-3rd-ecommerce
server:
  port: 9990